### PR TITLE
Version 1.0.1 - large overhaul

### PR DESCRIPTION
**Pull request by paul42**
Breaking Changes: 
- forgoing the x.mongoose.json strategy in favor of x-swagger-mongoose decoration on swagger documents

Added:
-Unique Indices
-Validator support (couldn't quite get pattern=>regex to work, so I did this workaround)

Other stuff?

### CODE REVIEW

**Comment by AilisObrian** [comment]
What is the blocking issue? What can I do for you!

**Comment by paul42** [comment]
I'm not certain what the blocker is - I'd like to merge but I don't have permissions.

**Comment by briananderson1222** [comment]
@simonguest : any help here?

**Comment by simonguest** [comment]
Sorry for the delay - for some reason, didn't get the notification of the new PR!

**Comment by paul42** [comment]
Good work team! I think there are a ton of great improvements here and I am excited to update my code to use this repo, ping me if there are any issues that arise from the large amount of breaking changes

**Pull request merged**
